# Generated by Django 5.2.1 on 2025-05-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_core', '0002_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacionkyc',
            name='documento_identidad',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
