# Generated by Django 5.2.1 on 2025-05-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('expirada', 'Expirada')], default='activa', max_length=10)),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'db_table': 'Sanciones',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
