# Generated by Django 5.2.1 on 2025-05-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(db_column='id_usuario')),
                ('id_juego', models.IntegerField(db_column='id_juego')),
                ('monto_apuesta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apuesta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'apuesta',
            },
        ),
    ]
